# Generated by Django 4.0.4 on 2023-11-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('dateregistration', models.DateField(auto_now_add=True)),
                ('datelastlogin', models.DateField(auto_now=True)),
            ],
        ),
    ]
