# Generated by Django 4.2.7 on 2023-11-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('cardinfo', models.CharField(max_length=45)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.user')),
            ],
        ),
    ]
