# Generated by Django 4.2.7 on 2023-11-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('firstusr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstusr_friendships_set', to='chats.user')),
                ('secondusr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondusr_friendships_set', to='chats.user')),
            ],
        ),
    ]
