# Generated by Django 4.2.7 on 2023-11-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chats'),
        ),
    ]
