# Generated by Django 4.2.7 on 2023-11-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.audio')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.user')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.video')),
            ],
        ),
    ]
